baseURL = "https://afnan.io"
languageCode = "en-us"
title = "afnan.io"
theme = "hugo-theme-monochrome"
pygmentscodefences = true
pygmentsUseClasses = true
canonifyurls = true
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Afnan Enayet"
sitename = "afnan.io"
description = "A personal site"
githubUsername = "afnanenayet"
showBorder = true
backgroundColor = "white"
font = "Source Sans Pro"
highlight = true
highlightLanguages = ["rust", "cpp", "python", "golang", "haskell"]
katexVersion = "0.13.1"
enable_zooming_js = true
enable_header_anchor = true
enable_toc = true
enable_site_search = true
enable_math = true

# syntax highlight settings
[params.syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

[params.syntax_highlight.builtin]
enable_code_copy = true

[params.syntax_highlight.prism]
enable_code_copy = true
enable_line_no = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noHl = false
noClasses = true
style = "one-dark"
tabWidth = 4

[[menu.navbar]]
url = "/about/"
name = "About"
weight = 1

[[menu.navbar]]
url = "/project/"
name = "Projects"
weight = 2

[[menu.navbar]]
url = "https://github.com/afnanenayet"
name = "Github"
weight = 3
